language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
install:
  - python -m pip install --upgrade pip wheel
  - pip install h5pyd -upgrade
  - pip install coveralls
  - pip install .
import:
  - .hscfg
script:
  - nosetests -v --with-coverage --cover-package=mhkit mhkit    
after_success:
  - coveralls
